installedESLint: true
parser: babel-eslint
extends: airbnb
env:
  browser: true
plugins:
  - react
ecmaFeatures:
  classes: true
  jsx: true
rules:
  global-require: 0
  no-undef: 0
  max-len: 0
  react/prop-types: 1
  react/react-in-jsx-scope: 0
  react/jsx-filename-extension: 0
  eqeqeq: 0
  object-curly-spacing: 0
  no-case-declarations: 0
  quotes: 0
  block-spacing: 0
  react/prefer-stateless-function: 0
